services:
  web:
    build:
      context: .
      dockerfile: ./docker/web/Dockerfile
    ports:
      - 8000:8000
    environment:
      - WEB_PORT=8000
      - WORKER_URL="http://worker:7711"
      - MONGO_URL="mongodb://mongo"
      - SELENIUM_URL="http://selenium:4444"
    depends_on:
      - mongo
      - selenium

  worker:
    build:
      context: .
      dockerfile: ./docker/worker/Dockerfile
    ports:
      - 7711:7711
    environment:
      - MONGO_URL="mongodb://mongo"
      - SELENIUM_URL="http://selenium:4444"
    depends_on:
      - mongo
      - selenium

  mongo:
    image: mongodb/mongodb-community-server:latest
    # environment:
    #   - MONGODB_INITDB_ROOT_USERNAME=user
    #   - MONGODB_INITDB_ROOT_PASSWORD=pass
    # volumes:
    #   - ./data:/data/db
    ports:
      - 27017:27017

  selenium:
    image: selenium/standalone-firefox
    shm_size: "2gb"
    ports:
      - 4444:4444
      - 7900:7900
