services:
  web:
    build:
      context: .
      dockerfile: ./docker/web/Dockerfile
    ports:
      - 8000:8000
    environment:
      - WEB_PORT=8000
      - WORKER_URL=http://worker:7711
      - MONGO_URL=mongodb://mongo
      - SELENIUM_URL=http://selenium:4444
    depends_on:
      - mongo
      - selenium

  worker:
    build:
      context: .
      dockerfile: ./docker/worker/Dockerfile
    ports:
      - 7711:7711
    volumes:
      - ./output:/app/output
    environment:
      - SAVE_DIR=/app/output
      - MONGO_URL=mongodb://mongo
      - SELENIUM_URL=http://selenium:4444
    depends_on:
      - mongo
      - selenium

  mongo:
    image: mongodb/mongodb-community-server:6.0-ubi8
    ports:
      - 27017:27017

  selenium:
    image: selenium/standalone-firefox
    shm_size: "2gb"
    ports:
      - 4444:4444
      - 7900:7900
